// <auto-generated />
namespace DiabetesFoodJournal.Data.Server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Proxy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Proxy));
        
        string IMigrationMetadata.Id
        {
            get { return "202005212232397_Proxy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
