name: Playoff Pool Build and Publish

on:
  push:
    branches: [ main ]
    paths:
      - '**/TypeOneDiabetesJournal/**'

jobs:
  build-food-journal-api:
    environment: development
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.*
    - name: Install dependencies
      working-directory: './src/TypeOneDiabetesJournal/WebApi'
      run: dotnet restore ./WebApi.csproj
    - name: Build Solution
      working-directory: './src/TypeOneDiabetesJournal/WebApi'
      run: dotnet build --configuration Release --no-restore ./WebApi.csproj
    - name: Run Unit Tests
      working-directory: './src/TypeOneDiabetesJournal/WebApi'
      run: dotnet test --no-restore --verbosity normal ./WebApi.csproj
    - name: Publish MVC Site
      working-directory: './src/TypeOneDiabetesJournal/WebApi'
      run: dotnet publish "./WebApi.csproj" -c Release -o publishFoodJournalApi --self-contained true -a x86
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: './src/TypeOneDiabetesJournal/publishFoodJournalApi/appsettings.json'
      env:
        ConnectionStrings.foodJournal: ${{ secrets.DB_CONNECTION_STRING }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: food-journal-api-artifact
        path: ./src/TypeOneDiabetesJournal/publishFoodJournalApi

  deploy-to-host-gator:
    name: Copy Files to HostGator
    needs: build-food-journal-api
    environment: development
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: food-journal-api-artifact
      - name: FTP Deploy MVC
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.FTP_FOOD_JOURNAL_API_USERNAME }}
          password: ${{ secrets.FTP_FOOD_JOURNAL_API_PASSWORD }}
          port: 21
          timeout: 1200000
          local-dir: ./
